Repository AY1920S1-CS2113-T16-1/main, pull requests merged in 2019-11, with the labels that each got.

#140 Add sort by done and type / Fix bug issue: 109, 122 and 133
  docs/[AY1920S1-CS2113-T16-1]-Le Duc-DG.adoc
  docs/[AY1920S1-CS2113-T16-1]-Le Duc-UG.adoc
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/main/java/leduc/command/SortCommand.java
  src/main/java/leduc/task/EventsTask.java
  src/main/java/leduc/task/HomeworkTask.java
  src/main/java/leduc/task/TodoTask.java
  src/test/java/leduc/SortCommandTest.java
Labels: priority.High, severity.Medium, type.Bug, type.Story

#141 Fix event bug : issue 111,112,113
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/exception/EventDateException.java
  src/main/java/leduc/task/TaskList.java
  src/test/java/leduc/EventCommandTest.java
  src/test/java/leduc/RescheduleCommandTest.java
Labels: severity.Medium, type.Bug

#142 Fix Edit bug: issue 115
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/main/java/leduc/command/EditCommand.java
Labels: severity.Medium, type.Bug

#143 Fix Prioritize bug: issue 127 and 129
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/PrioritizeCommand.java
  src/test/java/leduc/PrioritizeCommandTest.java
Labels: severity.Low, type.Bug

#144 Fix bugs
  docs/images/Ui.png
  src/main/java/leduc/Parser.java
  src/main/java/leduc/Ui.java
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/main/java/leduc/command/LanguageCommand.java
  src/main/java/leduc/command/ShortcutCommand.java
  src/main/java/leduc/storage/Storage.java
  src/test/java/leduc/UiFrTest.java
Labels: severity.Medium, type.Bug, type.Story

#148 add recurrence for event
  docs/team/[AY1920S1-CS2113-T16-1]-[Jerome Huang]PPP.adoc
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/exception/RecurrenceDateException.java
Labels: priority.High, type.Story

#151 add junit test for uiFr
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/test/java/leduc/EventCommandTest.java
  src/test/java/leduc/UiFrTest.java
Labels: severity.Low, type.Bug

#156 Find Feature Improvement/Bug Fix
  src/main/java/data/duke.txt
  src/main/java/leduc/command/FindCommand.java
Labels: type.Bug

#161 update and fix
  docs/[AY1920S1-CS2113-T16-1]-Le Duc-UG.adoc
  src/main/java/leduc/Duke.java
  src/main/java/leduc/command/ByeCommand.java
  src/main/java/leduc/command/Command.java
  src/main/java/leduc/command/DeleteCommand.java
  src/main/java/leduc/command/DoneCommand.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/command/FindCommand.java
  src/main/java/leduc/command/HelpCommand.java
  src/main/java/leduc/command/HomeworkCommand.java
  src/main/java/leduc/command/LanguageCommand.java
  src/main/java/leduc/command/ListCommand.java
  src/main/java/leduc/command/MeaninglessCommand.java
  src/main/java/leduc/command/PostponeCommand.java
  src/main/java/leduc/command/PrioritizeCommand.java
  src/main/java/leduc/command/RemindCommand.java
  src/main/java/leduc/command/RescheduleCommand.java
  src/main/java/leduc/command/SetWelcomeCommand.java
  src/main/java/leduc/command/ShortcutCommand.java
  src/main/java/leduc/command/ShowCommand.java
  src/main/java/leduc/command/SnoozeCommand.java
  src/main/java/leduc/command/SortCommand.java
  src/main/java/leduc/command/StatsCommand.java
  src/main/java/leduc/command/TodoCommand.java
  src/main/java/leduc/command/UnfinishedCommand.java
  src/main/java/leduc/exception/FileException.java
  src/main/java/leduc/exception/HomeworkTypeException.java
  src/main/java/leduc/exception/RecurrenceDateException.java
  src/main/java/leduc/exception/RecurrenceException.java
  src/main/java/leduc/exception/WrongParameterException.java
  src/main/java/leduc/storage/Storage.java
  src/main/java/leduc/ui/Ui.java
  src/main/java/leduc/ui/UiEn.java
  src/main/java/leduc/ui/UiFr.java
  src/test/java/leduc/DeadlineCommandTest.java
  src/test/java/leduc/EditCommandTest.java
  src/test/java/leduc/EventCommandTest.java
  src/test/java/leduc/PostponeCommandTest.java
  src/test/java/leduc/PrioritizeCommandTest.java
  src/test/java/leduc/RescheduleCommandTest.java
  src/test/java/leduc/ShowCommandTest.java
  src/test/java/leduc/SnoozeCommandTest.java
  src/test/java/leduc/SortCommandTest.java
  src/test/java/leduc/TodoCommandTest.java
  src/test/java/leduc/UiEnTest.java
  src/test/java/leduc/UiFrTest.java
Labels: severity.High, type.Bug

#162 Fix bug
  build.gradle
  src/main/java/leduc/Date.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/command/HomeworkCommand.java
  src/main/java/leduc/command/PostponeCommand.java
  src/main/java/leduc/command/PrioritizeCommand.java
  src/main/java/leduc/command/RescheduleCommand.java
  src/test/java/leduc/HomeworkCommandTest.java
Labels: severity.Medium, type.Bug
