Repository AY1920S1-CS2113-T16-1/main, pull requests merged in 2019-10, with the labels that each got.

#24 User Stories: Edit task
  src/main/java/leduc/Parser.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/task/DeadlinesTask.java
  src/main/java/leduc/task/EventsTask.java
  src/main/java/leduc/task/Task.java
  text-ui-test/runtest.sh
  text-ui-test/test6/ACTUAL6.TXT
  text-ui-test/test6/EXPECTED6.TXT
  text-ui-test/test6/input6.txt
  text-ui-test/test6/test6.txt
Labels: priority.High, type.Story

#25 help command
  src/main/java/leduc/Parser.java
  src/main/java/leduc/Ui.java
  src/main/java/leduc/command/HelpCommand.java
Labels: priority.Medium

#26 Clean the code
  src/main/java/leduc/Date.java
  src/main/java/leduc/command/DeadlineCommand.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/command/PostponeCommand.java
  src/main/java/leduc/command/RemindCommand.java
  src/main/java/leduc/command/RescheduleCommand.java
  src/main/java/leduc/command/TodoCommand.java
  src/main/java/leduc/task/DeadlinesTask.java
  src/main/java/leduc/task/EventsTask.java
  src/main/java/leduc/task/TaskList.java
Labels: priority.Medium

#64 Delete test7 folder and update help command
  src/main/java/leduc/Ui.java
  text-ui-test/test7/ACTUAL7.TXT
  text-ui-test/test7/EXPECTED7.TXT
  text-ui-test/test7/input7.txt
Labels: severity.Low

#65 Debug
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/RemindCommand.java
Labels: severity.Medium

#68 Early development of shortcut
  src/main/java/leduc/Parser.java
  src/main/java/leduc/command/ByeCommand.java
  src/main/java/leduc/command/DeadlineCommand.java
  src/main/java/leduc/command/DeleteCommand.java
  src/main/java/leduc/command/DoneCommand.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/command/FindCommand.java
  src/main/java/leduc/command/HelpCommand.java
  src/main/java/leduc/command/ListCommand.java
  src/main/java/leduc/command/PostponeCommand.java
  src/main/java/leduc/command/RemindCommand.java
  src/main/java/leduc/command/RescheduleCommand.java
  src/main/java/leduc/command/SetWelcomeCommand.java
  src/main/java/leduc/command/SnoozeCommand.java
  src/main/java/leduc/command/SortCommand.java
  src/main/java/leduc/command/TodoCommand.java
  src/test/testFile/EventCommand.txt
Labels: priority.High, type.Story

#77 Fix issue related to priority and load data file
  src/main/java/leduc/storage/Storage.java
  src/main/java/leduc/task/DeadlinesTask.java
  src/main/java/leduc/task/EventsTask.java
  src/main/java/leduc/task/Task.java
  src/main/java/leduc/task/TodoTask.java
Labels: severity.Medium

#76 Show by option
  data/duke.txt
  src/main/java/leduc/Parser.java
  src/main/java/leduc/Ui.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/command/FindCommand.java
  src/main/java/leduc/command/HelpCommand.java
  src/main/java/leduc/command/ListCommand.java
  src/main/java/leduc/command/PostponeCommand.java
  src/main/java/leduc/command/RemindCommand.java
  src/main/java/leduc/command/RescheduleCommand.java
  src/main/java/leduc/command/SetWelcomeCommand.java
  src/main/java/leduc/command/ShortcutCommand.java
  src/main/java/leduc/command/ShowCommand.java
  src/main/java/leduc/command/SnoozeCommand.java
  src/main/java/leduc/command/SortCommand.java
  src/main/java/leduc/command/TodoCommand.java
  src/main/java/leduc/exception/WrongParameterException.java
Labels: priority.High, severity.Low, type.Story

#80 Debug
  src/main/java/leduc/command/FindCommand.java
  src/main/java/leduc/command/RescheduleCommand.java
  text-ui-test/test7/ACTUAL7.TXT
  text-ui-test/test7/EXPECTED7.TXT
  text-ui-test/test7/input7.txt
Labels: severity.Medium, type.Bug

#82 shortcut respect the multi step constraint
  src/main/java/leduc/command/ShortcutCommand.java
Labels: severity.Low, type.Bug

#85 Clean the showCommand code a bit
  src/main/java/leduc/Parser.java
  src/main/java/leduc/Ui.java
  src/main/java/leduc/command/ShortcutCommand.java
  src/main/java/leduc/command/ShowCommand.java
  src/main/java/leduc/exception/MeaninglessException.java
  src/test/java/leduc/ShowCommandTest.java
  src/test/testFile/ShowCommandTest.txt
Labels: severity.Low, type.Enhancement

#99 One shot edit command and before/after in Junit
  data/duke.txt
  docs/[AY1920S1-CS2113-T16-1]-[Le Duc]-UG.adoc
  src/main/java/leduc/Parser.java
  src/main/java/leduc/Ui.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/exception/EditFormatException.java
  src/main/java/leduc/exception/UserAnswerException.java
  src/test/java/leduc/DeadlineCommandTest.java
  src/test/java/leduc/EditCommandTest.java
  src/test/java/leduc/EventCommandTest.java
  src/test/java/leduc/ParserTest.java
  src/test/java/leduc/PostponeCommandTest.java
  src/test/java/leduc/PrioritizeCommandTest.java
  src/test/java/leduc/RescheduleCommandTest.java
  src/test/java/leduc/ShowCommandTest.java
  src/test/java/leduc/SnoozeCommandTest.java
  src/test/java/leduc/SortCommandTest.java
  src/test/java/leduc/TodoCommandTest.java
  src/test/text-ui-test/runtest.sh
  src/test/text-ui-test/test6/ACTUAL6.TXT
  src/test/text-ui-test/test6/EXPECTED6.TXT
  src/test/text-ui-test/test6/test6.txt
Labels: priority.High, type.Story

#101 Add the possibily to change the language of the program
  src/main/java/leduc/Duke.java
  src/main/java/leduc/Parser.java
  src/main/java/leduc/Ui.java
  src/main/java/leduc/UiEn.java
  src/main/java/leduc/UiFr.java
  src/main/java/leduc/command/DeleteCommand.java
  src/main/java/leduc/command/DoneCommand.java
  src/main/java/leduc/command/EditCommand.java
  src/main/java/leduc/command/EventCommand.java
  src/main/java/leduc/command/FindCommand.java
  src/main/java/leduc/command/HomeworkCommand.java
  src/main/java/leduc/command/LanguageCommand.java
  src/main/java/leduc/command/ListCommand.java
  src/main/java/leduc/command/PostponeCommand.java
  src/main/java/leduc/command/PrioritizeCommand.java
  src/main/java/leduc/command/RemindCommand.java
  src/main/java/leduc/command/RescheduleCommand.java
  src/main/java/leduc/command/SetWelcomeCommand.java
  src/main/java/leduc/command/ShortcutCommand.java
  src/main/java/leduc/command/ShowCommand.java
  src/main/java/leduc/command/SnoozeCommand.java
  src/main/java/leduc/command/SortCommand.java
  src/main/java/leduc/command/StatsCommand.java
  src/main/java/leduc/command/TodoCommand.java
  src/main/java/leduc/exception/ConflictDateException.java
  src/main/java/leduc/storage/Storage.java
  src/test/java/leduc/DeadlineCommandTest.java
  src/test/java/leduc/EditCommandTest.java
  src/test/java/leduc/EventCommandTest.java
  src/test/java/leduc/PostponeCommandTest.java
  src/test/java/leduc/PrioritizeCommandTest.java
  src/test/java/leduc/RescheduleCommandTest.java
  src/test/java/leduc/ShowCommandTest.java
  src/test/java/leduc/SnoozeCommandTest.java
  src/test/java/leduc/SortCommandTest.java
  src/test/java/leduc/TodoCommandTest.java
  src/test/java/leduc/UiFrTest.java
Labels: priority.Medium, type.Story
